### PR TITLE
Converted remaining pages into global

### PR DESCRIPTION
**Pull request by tu2-atmanand**
Converted remaining pages into global css and kind of completed the Home page, if you guys feel any thing need to be done differently, we can first merge my branch into the global-styles and we can proceed with development on the global style branch, from there onwards.

I have no idea at what stage the main branch is at currently, so let decide afterwards, whether we should merge the global-styles branch also to main branch and clear out the multiple branches created and left open.

### CODE REVIEW

**Comment by Shridhar-dev** [comment]
1. This section needs refinement, the tags are overlapping
image


Also the styling in design is this way 👇
image


2. In this section the title and cards should start from the same point. The view more button should be placed in line with title

image

Same with the following section, also here the entire word should uppercased

image


3. BG colour. Aayein?
image

Rest is fine for now ✌️

**Comment by tu2-atmanand** [comment]
Ill update the issues for 2nd and 3rd sujjestion. For the 1st sujjestion, the word belt, lets create and issue, as i am facing it challenging to solve.

**Comment by tu2-atmanand** [comment]
I guess, for suggestion 3 the bgcolor looks fine as of now, we can change it to something else later, based on further UI improvement.
For Suggestion 1 i have created an issue. 
We can merge this branch as of now, and someone can take forward from the global-styles branch.

**Comment by tu2-atmanand** [comment]
Suggestion 2 done, we can merge the PR

**Pull request merged**
