### PR TITLE
Footer component

### LINKED ISSUE #7: feat: Footer
Tasks
- Footer Links:
  - Home route, Team route, GEC website link, Skill survey form link
- Copiable email component
- Social media links (using Tabler Icons/React Icons)
- Copyright and credits

image

### PR DESCRIPTION
**Pull request by Shriteen**
Also includes CopyableURL component designed to be generically usable
Screenshot 2023-08-24 at 18-08-17 Create Next App

Fixes #7

### CODE REVIEW

**Comment by Shridhar-dev** [comment]
Hey @Shriteen, some few changes:

image
The top and bottom padding of is uneven which can be seen when you hover on the icons, and also cursor becomes pointer only when you hover on the logo. Please make the padding even and let the cursor be pointer and clickable when you hover on the entire brown div.

image
Same cursor pointer on hover the brown div

Also its UI is slightly different from the one in the figma file, specifically the border-radius and the padding
image


Once this are done I guess the PR is good to merge

**Comment by Shriteen** [comment]
> Same cursor pointer on hover the brown div

I didn't got exactly which div you are referring to? Do you mean hover on entire div containing link and copy button  or only the button part?

**Comment by Shridhar-dev** [comment]
> > Same cursor pointer on hover the brown div
> 
> I didn't got exactly which div you are referring to? Do you mean hover on entire div containing link and copy button  or only the button part?
> 

Only the button part, it did not have cursor set to pointer

**Comment by Shriteen** [comment]
> Only the button part, it did not have cursor set to pointer

This is implemented now in [af641f4](https://github.com/Engicos-Coders-Club/club-official-website/pull/20/commits/af641f4b477688e6eb57474c4e2cd0cead1a57c7)

You may proceed with review/merge

**Review by Shridhar-dev — APPROVED** [review]

**Pull request merged**
